### ISSUE TITLE
`otk.target` aren't recognized if defined inside `otk.include`

### ISSUE THREAD

**Issue by ondrejbudai** [osbuild/otk#112]
`a.yaml`:

```
otk.version: '1'

otk.include.b: "b.yaml"

```

`b.yaml`:

```
otk.target.foo.bar:
  yolo: true
```

```
python3 -m otk validate ../a.yaml
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/obudai/work/otk/src/otk/__main__.py", line 3, in <module>
    root()
  File "/home/obudai/work/otk/src/otk/command.py", line 45, in root
    return validate(arguments)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/obudai/work/otk/src/otk/command.py", line 118, in validate
    return _process(arguments, dry_run=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/obudai/work/otk/src/otk/command.py", line 60, in _process
    doc = Omnifest.from_yaml_file(src)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/obudai/work/otk/src/otk/document.py", line 33, in from_yaml_file
    return cls.from_yaml_bytes(file.read())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/obudai/work/otk/src/otk/document.py", line 25, in from_yaml_bytes
    cls.ensure(deserialized_data)
  File "/home/obudai/work/otk/src/otk/document.py", line 64, in ensure
    raise ParseTargetError("omnifest must contain at least one key by the name of `%s.*`" % (PREFIX_TARGET,))
otk.error.ParseTargetError: omnifest must contain at least one key by the name of `otk.target..*`
```

**Comment by supakeen** [comment]
Yea, we should fix this. We should probably also change the entrypoint documentation to allow `otk.target` via includes.
