### ISSUE TITLE
Container not working due to missing `osbuild-gen-depsolve-dnf4`

### ISSUE THREAD

**Issue by supakeen** [osbuild/otk#284]
Pulling the latest container and trying the README command:

```
€ podman run -i -v .:/app:z ghcr.io/osbuild/otk compile /app/example/centos/centos-9-aarch64-tar.yaml
Traceback (most recent call last):
  File "/usr/local/bin/otk", line 8, in <module>
    sys.exit(root())
             ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/otk/command.py", line 14, in root
    return run(sys.argv[1:])
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/otk/command.py", line 32, in run
    return compile(arguments)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/otk/command.py", line 87, in compile
    return _process(arguments, dry_run=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/otk/command.py", line 55, in _process
    doc = Omnifest(path)
          ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/otk/document.py", line 31, in __init__
    tree = process_include(self._ctx, state, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/otk/transform.py", line 238, in process_include
    return resolve(ctx, state.copy(path=path), data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/otk/transform.py", line 61, in resolve
    return resolve_dict(ctx, state, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/otk/transform.py", line 94, in resolve_dict
    process_defines(ctx, state, val)
  File "/usr/local/lib/python3.12/site-packages/otk/transform.py", line 208, in process_defines
    process_defines(ctx, new_state, value)
  File "/usr/local/lib/python3.12/site-packages/otk/transform.py", line 208, in process_defines
    process_defines(ctx, new_state, value)
  File "/usr/local/lib/python3.12/site-packages/otk/transform.py", line 202, in process_defines
    new_vars = resolve(ctx, state, call(state, key, resolve(ctx, state, value)))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/otk/external.py", line 29, in call
    process = subprocess.run([exe], input=data, encoding="utf8", capture_output=True, check=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: PosixPath('/usr/local/libexec/otk/external/osbuild-gen-depsolve-dnf4')
```

**Comment by supakeen** [comment]
In the container we end up with a bunch of stuff in `/usr/local/libexec`, the executables in there for Python have their shebang set to `/src/venv/...` which doesn't exist in the actually produced container.
