### ISSUE TITLE
otk can't find externals after following the installation guide

### ISSUE THREAD

**Issue by thozza** [osbuild/otk#291]
After following https://github.com/osbuild/otk/blob/main/doc/00-installation.md and running `make external`, it seems that the `osbuild-*` binaries are symlinked to a different path, than those used by `otk` to look for them.

```console
$ make external
ln -sf /home/thozza/devel/otk/venv/bin/osbuild-* /home/thozza/devel/otk/external/
```
```console
$ otk validate example/rhel/9.6/rhel-9.6-aarch64-ami.yaml 
Traceback (most recent call last):
  File "/home/thozza/devel/otk/venv/bin/otk", line 8, in <module>
    sys.exit(root())
             ~~~~^^
  File "/home/thozza/devel/otk/src/otk/command.py", line 14, in root
    return run(sys.argv[1:])
  File "/home/thozza/devel/otk/src/otk/command.py", line 34, in run
    return validate(arguments)
  File "/home/thozza/devel/otk/src/otk/command.py", line 93, in validate
    return _process(arguments, dry_run=True)
  File "/home/thozza/devel/otk/src/otk/command.py", line 57, in _process
    doc = Omnifest(paths)
  File "/home/thozza/devel/otk/src/otk/document.py", line 36, in __init__
    tree = process_include(self._ctx, state, path)
  File "/home/thozza/devel/otk/src/otk/transform.py", line 238, in process_include
    return resolve(ctx, state.copy(path=path), data)
  File "/home/thozza/devel/otk/src/otk/transform.py", line 61, in resolve
    return resolve_dict(ctx, state, data)
  File "/home/thozza/devel/otk/src/otk/transform.py", line 94, in resolve_dict
    process_defines(ctx, state, val)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/thozza/devel/otk/src/otk/transform.py", line 208, in process_defines
    process_defines(ctx, new_state, value)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thozza/devel/otk/src/otk/transform.py", line 208, in process_defines
    process_defines(ctx, new_state, value)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thozza/devel/otk/src/otk/transform.py", line 202, in process_defines
    new_vars = resolve(ctx, state, call(state, key, resolve(ctx, state, value)))
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thozza/devel/otk/src/otk/external.py", line 21, in call
    exe = path_for(exe)
  File "/home/thozza/devel/otk/src/otk/external.py", line 62, in path_for
    raise RuntimeError(f"could not find {exe!r} in any search path {paths!r}")
RuntimeError: could not find 'osbuild-gen-depsolve-dnf4' in any search path ['/usr/local/libexec/otk/external', '/usr/libexec/otk/external', '/usr/local/lib/otk/external', '/usr/lib/otk/external']
```

**Comment by supakeen** [comment]
`OTK_EXTERNAL_PATH="./external" otk validate example/rhel/9.6/rhel-9.6-aarch64-ami.yaml` would be the answer, see [usage](https://github.com/osbuild/otk/blob/main/doc/02-usage.md#usage).
