### ISSUE TITLE
Crash when processing an unknown target

### ISSUE THREAD

**Issue by ondrejbudai** [osbuild/otk#95]
My omnifest:

```yaml
otk.version: 1
otk.target.test:
  yolo: true
```

Invocation:
```
otk compile -t test /data/omnifest.yaml
```

What I got:

```
Traceback (most recent call last):
  File "/usr/local/bin/otk", line 8, in <module>
    sys.exit(root())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/otk/command.py", line 154, in compile
    context = context_registry[kind](ctx)
KeyError: 'test'
```

**Comment by supakeen** [comment]
```
(venv) user@muja otk € otk compile -t osbuild-composer test.yaml
{
  "foo": "bar"
}
(venv) user@muja otk € cat test.yaml
otk.version: "1"

otk.target.osbuild-composer:
  foo: bar
```

Is how this works if #97 gets merged.
